DROP TABLE IF EXISTS "User" CASCADE;

DROP TABLE IF EXISTS "HousingUnit" CASCADE;

DROP TABLE IF EXISTS "Listing" CASCADE;

DROP TABLE IF EXISTS "Certification" CASCADE;

DROP TABLE IF EXISTS "Photo" CASCADE;

DROP TABLE IF EXISTS "Rating" CASCADE;

DROP TABLE IF EXISTS "Flag" CASCADE;

DROP TABLE IF EXISTS "HousingUnitHasCertification" CASCADE;
