version: "3.3"
services:
  db:
    container_name: ph_postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_DB: provohousing
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  postgrest:
    container_name: ph_postgrest
    image: postgrest/postgrest
    ports:
      - "8000:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://app_user:${POSTGRES_PASSWORD}@db:5432/provohousing
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: app_user
      PGRST_SERVER_PROXY_URI: "http://127.0.0.1:8000"
    depends_on:
      - db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: